//
// Created by Malcolm Hall on 4/19/23.
//

#ifndef RONASCRIPT_SRC_CODEGEN_BINARYREADER_H_
#define RONASCRIPT_SRC_CODEGEN_BINARYREADER_H_

class BinaryReader {};

#endif  //RONASCRIPT_SRC_CODEGEN_BINARYREADER_H_