name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: bash scripts/build.sh --target rebuild

    - name: Test
      working-directory: ${{github.workspace}}
      run: bash scripts/run_tests.sh --functional
      
#     - name: Publish Test Results
#       uses: EnricoMi/publish-unit-test-result-action/composite@v2
#       if: always()
#       with:
#         files: |
#           test/*.junit.xml

