name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    # TODO: Use output from build workflow to run tests
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: bash scripts/build.sh --target rebuild

    - name: Functional Tests
      working-directory: ${{github.workspace}}
      run: bash scripts/run_tests.sh --functional
      
    - name: Test Reporter
      uses: dorny/test-reporter@v1.6.0
      if: success() || failure()
      with:
        name: Test Results
        path: test/*.junit.xml
        reporter: jest-junit

